# This workflow will build a docker container, publish it to Github Packages, and deploy it to DigitalOcean k8s cluster when a release is created
name: Tests & Build Redash
on:
  push:
    branches: "tinrpt"

jobs:
  deploy-k8s:
    name: "Deployment"
    runs-on: ubuntu-latest
    needs: [buidl-redash]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup kubectl
        uses: matootie/dokube@v1.3.1
        with:
          personalAccessToken:  ${{ secrets.DIGITALOCEAN_TOKEN }}
          clusterName: ttek
          expirationTime: 300
          namespace: vts-dev

      - name: Define variables
        run: |
          export GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | awk '{print substr($0,0,7)}')
          echo "::set-env name=IMAGE_VERSION::$GITHUB_SHA_SHORT"

      - name: Setup Helm v3
        uses: azure/setup-helm@v1
        with:
          version: "v3.1.2"
          id: install

      - name: Install / Upgrade App
        run: |
          helm upgrade  --install ra --namespace=ra --values ./helm/values.yaml ./helm \
            --set image.tag=dev-95b8012
